name: Deploy Botmania

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Nuke NPM Lock
        working-directory: ./frontend
        run: rm -rf package-lock.json node_modules

      - name: Install with Yarn
        working-directory: ./frontend
        run: yarn install

      - name: Build Project
        working-directory: ./frontend
        run: yarn build

      # Mantenemos este paso de seguridad para normalizar 'dist' o 'build'
      - name: Prepare Artifact
        working-directory: ./frontend
        run: |
          if [ -d "dist" ]; then
            mv dist deploy_artifact
          elif [ -d "build" ]; then
            mv build deploy_artifact
          else
            echo "ERROR: No se encontró build ni dist"
            exit 1
          fi

      - name: FTP Upload
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Carpeta local (normalizada en el paso anterior)
          local-dir: ./frontend/deploy_artifact/
          # SOLUCIÓN: Usamos './' porque el usuario FTP ya inicia en la carpeta correcta
          server-dir: ./
          protocol: ftp
